name: quiz_it
description: A simple quiz application

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^2.8.11
  cupertino_icons: ^0.1.3
  html_unescape: ^1.0.1+3
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/
