name: quiz_it
description: A simple flutter quiz app which uses Redux for quiz state management.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^13.1.0
  cupertino_icons: ^1.0.4
  html_unescape: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.3

flutter:
  uses-material-design: true
  assets:
    - assets/
