import 'package:quiz_it/models/data.dart';

List<Data> categories = [
  Data(key: "", value: "Any Category"),
  Data(key: "9", value: "General Knowledge"),
  Data(key: "10", value: "Entertainment: Books"),
  Data(key: "11", value: "Entertainment: Film"),
  Data(key: "12", value: "Entertainment: Music"),
  Data(key: "13", value: "Entertainment: Musicals & Theatres"),
  Data(key: "14", value: "Entertainment: Television"),
  Data(key: "15", value: "Entertainment: Video Games"),
  Data(key: "16", value: "Entertainment: Board Games"),
  Data(key: "17", value: "Science & Nature"),
  Data(key: "18", value: "Science: Computers"),
  Data(key: "19", value: "Science: Mathematics"),
  Data(key: "20", value: "Mythology"),
  Data(key: "21", value: "Sports"),
  Data(key: "22", value: "Geography"),
  Data(key: "23", value: "History"),
  Data(key: "24", value: "Politics"),
  Data(key: "25", value: "Art"),
  Data(key: "26", value: "Celebrities"),
  Data(key: "27", value: "Animals"),
  Data(key: "28", value: "Vehicles"),
  Data(key: "29", value: "Entertainment: Comics"),
  Data(key: "30", value: "Science: Gadgets"),
  Data(key: "31", value: "Entertainment: Japanese Anime & Manga"),
  Data(key: "32", value: "Entertainment: Cartoon & Animations"),
];
